### ISSUE TITLE
install cypress on circleci

### ISSUE THREAD

**Issue by jorahood** [indiana-university/itpeople-app#49]
It would be good to run the e2e tests as part of ci. To install the cypress orb on circleci requires admin access to change two circleci config options, according to https://github.com/cypress-io/circleci-orb

Note ⚠️: To use CircleCI Orbs in your projects, you need to enable two settings:

    from organization settings allow using uncertified orbs Settings -> Security -> Allow uncertified orbs
    from the project's settings allow beta features Settings -> Advanced Settings -> Enable build processing (preview)

**Comment by jhoerr** [comment]
@jorahood I updated the settings, though they were a little different than described here. (Maybe the UI changed?)

**Comment by jhoerr** [comment]
I think this is working as expected.
